version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: daily
    open-pull-request-limit: 10
    commit-message:
      prefix: ci
      include: scope
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-request-limit: 10
    commit-message:
      prefix: fix
      prefix-development: build
      include: scope
