queue_rules:
  - name: dependabot
    queue_conditions:
      - status-success=all-checks-passed
      - base=main
      - author=dependabot[bot]
    merge_conditions:
      - status-success=all-checks-passed
    merge_method: merge

pull_request_rules:
  - name: dependabot
    conditions: []
    actions:
      queue:
