name: Runs versioned-files
description: Runs versioned-files

inputs:
  action:
    description: The versioned-files action to run
    required: true
  version:
    description: The version to update to
    required: true

runs:
  using: composite
  steps:
    - uses: tomphp/versioned-files/github-actions/setup-versioned-files@v0.3.0
      name: Install versioned-files

    - name: Run versioned-files
      id: get-version
      env:
        ACTION: ${{ inputs.action }}
        VERSION: ${{ inputs.version }}
      run: |
        set -euo pipefail

        if [ "$ACTION" == "update" ]; then
          versioned-files update "$VERSION"
        else
          echo "Unknown action '$ACTION'" >&2
          exit 1
        fi
      shell: bash
