name: Setup Versioned Files Action
description: Setup versioned-files on the path in your GitHub Actions job
branding:
  icon: arrow-down
  color: blue

inputs:
  version:
    description: Version of versioned-files to install
    required: false
    default: 'latest'

outputs:
  version:
    description: The version on the path
    value: ${{ steps.get-version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install versioned-files
      uses: tomphp/github-actions/install-release-binary@v0.5.0
      with:
        binary-name: versioned-files
        owner: tomphp
        repository: versioned-files
        version: ${{ inputs.version }}

    - name: Get Installed Version
      id: get-version
      run: echo "version=$( versioned-files --version | cut -d " " -f2 )" >> "$GITHUB_OUTPUT"
      shell: bash
