name: Test Github Actions
on:
  workflow_call:

jobs:
  test-setup-versioned-files:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./github-actions/setup-versioned-files
      - run: versioned-files --version
